import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class TermsScreen extends StatefulWidget {
  const TermsScreen({super.key});

  @override
  State<TermsScreen> createState() => _TermsScreenState();
}

class _TermsScreenState extends State<TermsScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8F9FB),
      appBar: AppBar(
        title: Text('Terms & Privacy',
            style: GoogleFonts.inter(
                fontWeight: FontWeight.w700, fontSize: 18, color: Colors.black)),
        backgroundColor: Colors.white,
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.black),
        centerTitle: true,
        surfaceTintColor: Colors.white,
        bottom: TabBar(
          controller: _tabController,
          labelColor: const Color(0xFF3182CE),
          unselectedLabelColor: Colors.grey.shade500,
          labelStyle: GoogleFonts.inter(fontWeight: FontWeight.w700, fontSize: 13),
          unselectedLabelStyle:
              GoogleFonts.inter(fontWeight: FontWeight.w500, fontSize: 13),
          indicatorColor: const Color(0xFF3182CE),
          indicatorWeight: 2.5,
          tabs: const [
            Tab(text: 'Terms & Conditions'),
            Tab(text: 'Privacy Policy'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _buildTermsTab(),
          _buildPrivacyTab(),
        ],
      ),
    );
  }

  // ──────────────────────────────────────────────
  // TERMS & CONDITIONS TAB
  // ──────────────────────────────────────────────
  Widget _buildTermsTab() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _headerCard(
            icon: Icons.gavel_rounded,
            title: 'Terms & Conditions',
            subtitle:
                'By using PesaCrow, you agree to the following terms. Please read them carefully.',
            gradient: const [Color(0xFF1A1A2E), Color(0xFF16213E)],
          ),
          const SizedBox(height: 24),

          _buildSection(
            '1. Parties Involved',
            'This Agreement is entered into between:\n\n'
            '• The Escrow Agent: PesaCrow (operated by A3s — Absolute Advanced Anonymity Services), a digital platform providing neutral holding and disbursement services.\n\n'
            '• The Buyer: Any natural or legal person utilizing PesaCrow to secure a purchase of goods or services.\n\n'
            '• The Seller: Any natural or legal person utilizing PesaCrow to secure payment for the provision of goods or services.\n\n'
            '• Participating Financial Institutions: Specifically Safaricom M-Pesa, which acts as the underlying payment rail for fund collection and disbursement.',
          ),

          _buildSection(
            '2. Definitions',
            '• "Escrow Account": The digital wallet or platform-managed record where funds are held until conditions are met.\n\n'
            '• "Escrowed Funds": The specific monetary amount (KES) deposited by the Buyer for a transaction.\n\n'
            '• "Disbursement": The act of releasing funds from the Escrow Account to the Seller or Buyer.\n\n'
            '• "Inspection Period": The timeframe agreed upon for the Buyer to verify the quality of goods/services.\n\n'
            '• "Business Day": Any day excluding weekends and public holidays in Kenya.\n\n'
            '• "Deal ID": The unique transaction identifier generated by the PesaCrow platform.',
          ),

          _buildSection(
            '3. Appointment of the Escrow Agent',
            'The Buyer and Seller hereby formally appoint PesaCrow as their neutral Escrow Agent. PesaCrow accepts this appointment and agrees to act solely as a facilitator in accordance with the automated logic of the platform and these terms. PesaCrow remains independent and does not represent either party in the underlying commerce.',
          ),

          _buildSection(
            '4. Description of the Escrowed Property',
            'PesaCrow facilitates the escrow of Kenyan Shillings (KES).\n\n'
            '• Deposits: Must be made exclusively via the Buyer\'s registered M-Pesa number through the PesaCrow STK Push prompt.\n\n'
            '• Limits: Minimum and maximum transaction limits apply as dictated by Safaricom M-Pesa regulations and PesaCrow internal policies.',
          ),

          _buildSection(
            '5. Release / Disbursement Conditions',
            'Funds are released from the Escrow Account under the following conditions:\n\n'
            '1. Mutual Approval: The Buyer confirms receipt and satisfaction of the goods/services through the platform, triggering an immediate release.\n\n'
            '2. Seller Proof of Delivery: In specific cases where proof of delivery is undisputed and the inspection period expires without a claim.\n\n'
            '3. Dispute Resolution: Upon a final decision by a PesaCrow Admin or an arbitrator in a disputed case.\n\n'
            '4. Automatic Expiry: If a deal is cancelled or fails to be approved within the platform\'s defined timeout periods, funds may be returned to the Buyer (less applicable fees).',
          ),

          _buildSection(
            '6. Fees and Expenses',
            'PesaCrow charges for its services to ensure platform stability and security.\n\n'
            '• Service Fees: Calculated as a combination of a fixed percentage and a flat transaction fee (refer to the "Fee Calculator" in-app).\n\n'
            '• Payment Rails: Standard M-Pesa transaction costs apply for sending and receiving via the platform.\n\n'
            '• Deduction: Fees are automatically deducted at the point of release or during the initial deposit as specified in the transaction breakdown.',
          ),

          _buildSection(
            '7. Duties and Responsibilities of the Escrow Agent',
            '• Neutrality: PesaCrow will act as a neutral third party and will not favor one party over another.\n\n'
            '• Reporting: PesaCrow provides a digital ledger of all transaction statuses within the platform dashboard.\n\n'
            '• Limitations: PesaCrow is responsible only for the safekeeping of funds and their disbursement according to user instructions; it does not warrant the quality, legality, or suitability of the underlying goods.',
          ),

          _buildSection(
            '8. Liability and Limitations of Liability',
            'PesaCrow is not liable for:\n\n'
            '• Disputes arising from the quality of goods or services provided by the Seller.\n\n'
            '• Losses due to network failures, Safaricom M-Pesa outages, or incorrect phone number entry by the user.\n\n'
            '• Indirect, incidental, or consequential damages.\n\n'
            '• Indemnification: Users agree to indemnify PesaCrow against all claims arising from their use of the platform in violation of these terms.',
          ),

          _buildSection(
            '9. Dispute Resolution',
            '• Mediation: The parties are encouraged to resolve the issue directly through the platform\'s "Dispute" feature.\n\n'
            '• Escalation: If unresolved after 48 hours, either party may escalate the deal to "Dispute" status.\n\n'
            '• Admin Decision: PesaCrow Admins will review the evidence (proof of delivery, communication logs) and issue a binding decision.\n\n'
            '• Legal Action: This Agreement is governed by the laws of the Republic of Kenya.',
          ),

          _buildSection(
            '10. Termination of Escrow',
            'The escrow relationship terminates when:\n\n'
            '• Funds are fully disbursed to the Seller.\n\n'
            '• Funds are returned to the Buyer.\n\n'
            '• The deal is cancelled by mutual agreement before the Seller has delivered.',
          ),

          _buildSection(
            '11. Interest / Investment of Funds',
            'Escrowed funds held by PesaCrow do not earn interest for the Buyer or Seller. PesaCrow does not invest escrowed funds in high-risk assets.',
          ),

          _buildSection(
            '12. Representations and Warranties',
            'Users represent that:\n\n'
            '• They have the legal capacity to enter this agreement.\n\n'
            '• The funds used are from legitimate sources.\n\n'
            '• The transaction does not involve illegal goods (e.g., drugs, weapons, or counterfeit items).',
          ),

          _buildSection(
            '13. Compliance and Regulatory Clauses',
            'PesaCrow adheres to Anti-Money Laundering (AML) and Know Your Customer (KYC) regulations. We reserve the right to flag and freeze transactions suspected of fraud or illegal activity and report them to relevant Kenyan authorities.',
          ),

          _buildSection(
            '14. General Provisions',
            '• Entire Agreement: These terms constitute the full agreement between the parties.\n\n'
            '• Amendments: Terms may be updated periodically; continued use of the platform constitutes acceptance.\n\n'
            '• Force Majeure: PesaCrow is not liable for delays caused by "Acts of God," pandemics, or civil unrest.',
          ),

          _buildSection(
            '15. Miscellaneous',
            'PesaCrow maintains no interest in the underlying transaction beyond the collection of service fees. Certain clauses, including Liability and Indemnification, survive the termination of this Agreement.',
          ),

          const SizedBox(height: 40),
        ],
      ),
    );
  }

  // ──────────────────────────────────────────────
  // PRIVACY POLICY TAB
  // ──────────────────────────────────────────────
  Widget _buildPrivacyTab() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _headerCard(
            icon: Icons.privacy_tip_outlined,
            title: 'Privacy Policy',
            subtitle: 'Effective Date: April 2026',
            gradient: const [Color(0xFF2E7D50), Color(0xFF1A4D30)],
          ),
          const SizedBox(height: 24),

          _buildSection(
            '1. Introduction',
            'Welcome to PesaCrow ("we", "our", or "us"), operated by A3s (Absolute Advanced Anonymity Services). We respect your privacy and are committed to protecting your personal data. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our platform or use our digital escrow services.',
          ),
          _buildSection(
            '2. Information We Collect',
            'To provide our digital escrow services effectively, we collect the following types of information:\n\n'
            '• Personal Identification Information: Phone number (M-Pesa registered number).\n\n'
            '• Transaction Information: Details regarding the deals you create or participate in, including Deal IDs, amounts, item descriptions, and M-Pesa transaction references.\n\n'
            '• Communication Data: Dispute evidence, or other communications made through the platform between Buyers, Sellers, and PesaCrow Admins.',
          ),
          _buildSection(
            '3. How We Use Your Information',
            'We use the collected information for the following purposes:\n\n'
            '• Service Delivery: To facilitate and manage escrow transactions, process M-Pesa deposits and disbursements, and update transaction statuses.\n\n'
            '• Dispute Resolution: To provide evidence to our Admins in the event of a dispute, allowing for fair and accurate resolutions.\n\n'
            '• Security and Compliance: To verify your identity, prevent fraud, monitor for unauthorized activities, and comply with AML and KYC regulations in Kenya.\n\n'
            '• Communication: To send you transactional notifications and respond to your customer service inquiries.',
          ),
          _buildSection(
            '4. Information Sharing and Disclosure',
            'We do not sell your personal data. We may share your information only in the following circumstances:\n\n'
            '• With the Other Party in a Deal: We share necessary information with the Buyer or Seller you are transacting with to facilitate the deal.\n\n'
            '• Service Providers: We share data with trusted third-party service providers, primarily Safaricom (M-Pesa).\n\n'
            '• Legal Obligations: We may disclose your information to law enforcement or regulatory authorities if required by Kenyan law.',
          ),
          _buildSection(
            '5. Data Security',
            'We implement industry-standard administrative, technical, and physical security measures to protect your personal information. Our platform uses encryption and secure protocols to safeguard sensitive data.',
          ),
          _buildSection(
            '6. Data Retention',
            'We retain your personal information only for as long as is necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law.',
          ),
          _buildSection(
            '7. Your Privacy Rights',
            'Depending on the applicable data protection laws in Kenya, you may have the right to access, correct, or delete your personal data. To exercise any of these rights, please contact our support team.',
          ),
          _buildSection(
            '8. Changes to This Privacy Policy',
            'We may update this Privacy Policy from time to time. We encourage you to review this page periodically for the latest information.',
          ),
          _buildSection(
            '9. Contact Us',
            'If you have any questions or concerns, please contact us at:\n\n'
            '• Email: support@pesacrow.top\n'
            '• Address: Nairobi, Kenya',
          ),
          const SizedBox(height: 40),
        ],
      ),
    );
  }

  // ──────────────────────────────────────────────
  // SHARED WIDGETS
  // ──────────────────────────────────────────────
  Widget _headerCard({
    required IconData icon,
    required String title,
    required String subtitle,
    required List<Color> gradient,
  }) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: gradient,
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(children: [
            Icon(icon, color: Colors.white, size: 22),
            const SizedBox(width: 10),
            Text(title,
                style: GoogleFonts.inter(
                    fontSize: 16,
                    fontWeight: FontWeight.w800,
                    color: Colors.white)),
          ]),
          const SizedBox(height: 8),
          Text(
            subtitle,
            style: TextStyle(
                fontSize: 12,
                color: Colors.white.withOpacity(0.8),
                height: 1.5),
          ),
        ],
      ),
    );
  }

  Widget _buildSection(String title, String content) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey.shade100),
      ),
      child: ExpansionTile(
        tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
        title: Text(
          title,
          style: GoogleFonts.inter(
              fontSize: 14,
              fontWeight: FontWeight.w700,
              color: const Color(0xFF1A1A1A)),
        ),
        iconColor: Colors.grey.shade600,
        collapsedIconColor: Colors.grey.shade400,
        childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
        expandedCrossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            content,
            style: TextStyle(
                fontSize: 13, color: Colors.grey.shade700, height: 1.7),
          ),
        ],
      ),
    );
  }
}
